// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Circulo', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('Circulo', async function () {
    await driver.get("http://localhost:3000")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    settimeout(3000)
    await driver.findElement(By.id("AAAAAAAAAAHG")).click()
    settimeout(3000)
    await driver.findElement(By.linkText("Círculo")).click()
    settimeout(3000)
    await driver.findElement(By.id("input")).click()
    await driver.findElement(By.id("input")).sendKeys("10")
    settimeout(3000)
    await driver.findElement(By.id("button")).click()
    settimeout(3000)
    if (! (await driver.findElement(By.id("response1")).getText() == "Perímetro: 314.1592653589793" && await driver.findElement(By.id("response2")).getText() == "Área: 62.83185307179586" )) {
      
      throw error();
    } else {
      settimeout(3000)
      console.log("todo bien")
      await driver.close()
    }

  })
})


function settimeout(tiempo) {
  let a = 0
  while (a < (tiempo * 1000000)) a++
}