// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Fibonacci', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('Fibonacci', async function () {
    await driver.get("http://localhost:3000/fibonacci")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    settimeout(3000)
    await driver.findElement(By.id("AAAAAAAAAAHG")).click()
    settimeout(3000)
    await driver.findElement(By.id("input")).click()
    await driver.findElement(By.id("input")).sendKeys("10")
    settimeout(3000)
    await driver.findElement(By.id("button")).click()
    settimeout(3000)
    //console.log(await driver.findElement(By.id("mensajeError")).getText())
    if (!(await driver.findElement(By.id("response")).getText()) == "0,1,1,2,3,5,8,13,21,34") {
      throw console.error();
    } else {
      settimeout(3000)

      await driver.close()
    }

  })
})


function settimeout(tiempo) {
  let a = 0
  while (a < (tiempo * 1000000)) a++
}