// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Triangulo', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('Triangulo', async function () {
    await driver.get("http://localhost:3000")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    settimeout(3000)
    await driver.findElement(By.id("AAAAAAAAAAHG")).click()
    settimeout(3000)
    await driver.findElement(By.linkText("Triángulo")).click()
    settimeout(3000)
    await driver.findElement(By.id("input1")).click()
    await driver.findElement(By.id("input1")).sendKeys("10")
    await driver.findElement(By.id("input2")).click()
    await driver.findElement(By.id("input2")).sendKeys("10")
    await driver.findElement(By.id("input3")).click()
    await driver.findElement(By.id("input3")).sendKeys("100")
    settimeout(3000)
    await driver.findElement(By.id("button")).click()
    settimeout(3000)
    if (! (await driver.findElement(By.id("response3")).getText() == "Error: Triángulo no válido" )) {
      
      throw error();
    } else {
      settimeout(3000)
      console.log("todo bien")
      await driver.close()
    }

  })
})


function settimeout(tiempo) {
  let a = 0
  while (a < (tiempo * 1000000)) a++
}